// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#ifndef PROTOBUF_data_2eproto__INCLUDED
#define PROTOBUF_data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace antalk {
namespace data {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_data_2eproto();
void protobuf_AssignDesc_data_2eproto();
void protobuf_ShutdownFile_data_2eproto();

class GetUserInfoReq;
class GetUserInfoRes;
class SetUserStatusReq;
class SetUserStatusResp;

// ===================================================================

class GetUserInfoReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:antalk.data.GetUserInfoReq) */ {
 public:
  GetUserInfoReq();
  virtual ~GetUserInfoReq();

  GetUserInfoReq(const GetUserInfoReq& from);

  inline GetUserInfoReq& operator=(const GetUserInfoReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetUserInfoReq& default_instance();

  void Swap(GetUserInfoReq* other);

  // implements Message ----------------------------------------------

  inline GetUserInfoReq* New() const { return New(NULL); }

  GetUserInfoReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetUserInfoReq& from);
  void MergeFrom(const GetUserInfoReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetUserInfoReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 saas_id = 1;
  bool has_saas_id() const;
  void clear_saas_id();
  static const int kSaasIdFieldNumber = 1;
  ::google::protobuf::uint32 saas_id() const;
  void set_saas_id(::google::protobuf::uint32 value);

  // required uint32 user_id = 2;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:antalk.data.GetUserInfoReq)
 private:
  inline void set_has_saas_id();
  inline void clear_has_saas_id();
  inline void set_has_user_id();
  inline void clear_has_user_id();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 saas_id_;
  ::google::protobuf::uint32 user_id_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static GetUserInfoReq* default_instance_;
};
// -------------------------------------------------------------------

class GetUserInfoRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:antalk.data.GetUserInfoRes) */ {
 public:
  GetUserInfoRes();
  virtual ~GetUserInfoRes();

  GetUserInfoRes(const GetUserInfoRes& from);

  inline GetUserInfoRes& operator=(const GetUserInfoRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetUserInfoRes& default_instance();

  void Swap(GetUserInfoRes* other);

  // implements Message ----------------------------------------------

  inline GetUserInfoRes* New() const { return New(NULL); }

  GetUserInfoRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetUserInfoRes& from);
  void MergeFrom(const GetUserInfoRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetUserInfoRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .antalk.common.UserInfo user_info = 1;
  bool has_user_info() const;
  void clear_user_info();
  static const int kUserInfoFieldNumber = 1;
  const ::antalk::common::UserInfo& user_info() const;
  ::antalk::common::UserInfo* mutable_user_info();
  ::antalk::common::UserInfo* release_user_info();
  void set_allocated_user_info(::antalk::common::UserInfo* user_info);

  // @@protoc_insertion_point(class_scope:antalk.data.GetUserInfoRes)
 private:
  inline void set_has_user_info();
  inline void clear_has_user_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::antalk::common::UserInfo* user_info_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static GetUserInfoRes* default_instance_;
};
// -------------------------------------------------------------------

class SetUserStatusReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:antalk.data.SetUserStatusReq) */ {
 public:
  SetUserStatusReq();
  virtual ~SetUserStatusReq();

  SetUserStatusReq(const SetUserStatusReq& from);

  inline SetUserStatusReq& operator=(const SetUserStatusReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetUserStatusReq& default_instance();

  void Swap(SetUserStatusReq* other);

  // implements Message ----------------------------------------------

  inline SetUserStatusReq* New() const { return New(NULL); }

  SetUserStatusReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetUserStatusReq& from);
  void MergeFrom(const SetUserStatusReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetUserStatusReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string uid = 1;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  const ::std::string& uid() const;
  void set_uid(const ::std::string& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  ::std::string* mutable_uid();
  ::std::string* release_uid();
  void set_allocated_uid(::std::string* uid);

  // optional int32 dev_type = 2;
  bool has_dev_type() const;
  void clear_dev_type();
  static const int kDevTypeFieldNumber = 2;
  ::google::protobuf::int32 dev_type() const;
  void set_dev_type(::google::protobuf::int32 value);

  // optional string session = 3;
  bool has_session() const;
  void clear_session();
  static const int kSessionFieldNumber = 3;
  const ::std::string& session() const;
  void set_session(const ::std::string& value);
  void set_session(const char* value);
  void set_session(const char* value, size_t size);
  ::std::string* mutable_session();
  ::std::string* release_session();
  void set_allocated_session(::std::string* session);

  // optional int32 status = 4;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional string login_info = 5;
  bool has_login_info() const;
  void clear_login_info();
  static const int kLoginInfoFieldNumber = 5;
  const ::std::string& login_info() const;
  void set_login_info(const ::std::string& value);
  void set_login_info(const char* value);
  void set_login_info(const char* value, size_t size);
  ::std::string* mutable_login_info();
  ::std::string* release_login_info();
  void set_allocated_login_info(::std::string* login_info);

  // @@protoc_insertion_point(class_scope:antalk.data.SetUserStatusReq)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_dev_type();
  inline void clear_has_dev_type();
  inline void set_has_session();
  inline void clear_has_session();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_login_info();
  inline void clear_has_login_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr uid_;
  ::google::protobuf::internal::ArenaStringPtr session_;
  ::google::protobuf::int32 dev_type_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::internal::ArenaStringPtr login_info_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static SetUserStatusReq* default_instance_;
};
// -------------------------------------------------------------------

class SetUserStatusResp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:antalk.data.SetUserStatusResp) */ {
 public:
  SetUserStatusResp();
  virtual ~SetUserStatusResp();

  SetUserStatusResp(const SetUserStatusResp& from);

  inline SetUserStatusResp& operator=(const SetUserStatusResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetUserStatusResp& default_instance();

  void Swap(SetUserStatusResp* other);

  // implements Message ----------------------------------------------

  inline SetUserStatusResp* New() const { return New(NULL); }

  SetUserStatusResp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetUserStatusResp& from);
  void MergeFrom(const SetUserStatusResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetUserStatusResp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .antalk.common.ResultType result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::antalk::common::ResultType result() const;
  void set_result(::antalk::common::ResultType value);

  // @@protoc_insertion_point(class_scope:antalk.data.SetUserStatusResp)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int result_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static SetUserStatusResp* default_instance_;
};
// ===================================================================

class UserStatusService_Stub;

class UserStatusService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline UserStatusService() {};
 public:
  virtual ~UserStatusService();

  typedef UserStatusService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void GetUserInfo(::google::protobuf::RpcController* controller,
                       const ::antalk::data::GetUserInfoReq* request,
                       ::antalk::data::GetUserInfoRes* response,
                       ::google::protobuf::Closure* done);
  virtual void SetUserStatus(::google::protobuf::RpcController* controller,
                       const ::antalk::data::SetUserStatusReq* request,
                       ::antalk::data::SetUserStatusResp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(UserStatusService);
};

class UserStatusService_Stub : public UserStatusService {
 public:
  UserStatusService_Stub(::google::protobuf::RpcChannel* channel);
  UserStatusService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~UserStatusService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements UserStatusService ------------------------------------------

  void GetUserInfo(::google::protobuf::RpcController* controller,
                       const ::antalk::data::GetUserInfoReq* request,
                       ::antalk::data::GetUserInfoRes* response,
                       ::google::protobuf::Closure* done);
  void SetUserStatus(::google::protobuf::RpcController* controller,
                       const ::antalk::data::SetUserStatusReq* request,
                       ::antalk::data::SetUserStatusResp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(UserStatusService_Stub);
};


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetUserInfoReq

// required uint32 saas_id = 1;
inline bool GetUserInfoReq::has_saas_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetUserInfoReq::set_has_saas_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetUserInfoReq::clear_has_saas_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetUserInfoReq::clear_saas_id() {
  saas_id_ = 0u;
  clear_has_saas_id();
}
inline ::google::protobuf::uint32 GetUserInfoReq::saas_id() const {
  // @@protoc_insertion_point(field_get:antalk.data.GetUserInfoReq.saas_id)
  return saas_id_;
}
inline void GetUserInfoReq::set_saas_id(::google::protobuf::uint32 value) {
  set_has_saas_id();
  saas_id_ = value;
  // @@protoc_insertion_point(field_set:antalk.data.GetUserInfoReq.saas_id)
}

// required uint32 user_id = 2;
inline bool GetUserInfoReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetUserInfoReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetUserInfoReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetUserInfoReq::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 GetUserInfoReq::user_id() const {
  // @@protoc_insertion_point(field_get:antalk.data.GetUserInfoReq.user_id)
  return user_id_;
}
inline void GetUserInfoReq::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:antalk.data.GetUserInfoReq.user_id)
}

// -------------------------------------------------------------------

// GetUserInfoRes

// required .antalk.common.UserInfo user_info = 1;
inline bool GetUserInfoRes::has_user_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetUserInfoRes::set_has_user_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetUserInfoRes::clear_has_user_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetUserInfoRes::clear_user_info() {
  if (user_info_ != NULL) user_info_->::antalk::common::UserInfo::Clear();
  clear_has_user_info();
}
inline const ::antalk::common::UserInfo& GetUserInfoRes::user_info() const {
  // @@protoc_insertion_point(field_get:antalk.data.GetUserInfoRes.user_info)
  return user_info_ != NULL ? *user_info_ : *default_instance_->user_info_;
}
inline ::antalk::common::UserInfo* GetUserInfoRes::mutable_user_info() {
  set_has_user_info();
  if (user_info_ == NULL) {
    user_info_ = new ::antalk::common::UserInfo;
  }
  // @@protoc_insertion_point(field_mutable:antalk.data.GetUserInfoRes.user_info)
  return user_info_;
}
inline ::antalk::common::UserInfo* GetUserInfoRes::release_user_info() {
  // @@protoc_insertion_point(field_release:antalk.data.GetUserInfoRes.user_info)
  clear_has_user_info();
  ::antalk::common::UserInfo* temp = user_info_;
  user_info_ = NULL;
  return temp;
}
inline void GetUserInfoRes::set_allocated_user_info(::antalk::common::UserInfo* user_info) {
  delete user_info_;
  user_info_ = user_info;
  if (user_info) {
    set_has_user_info();
  } else {
    clear_has_user_info();
  }
  // @@protoc_insertion_point(field_set_allocated:antalk.data.GetUserInfoRes.user_info)
}

// -------------------------------------------------------------------

// SetUserStatusReq

// optional string uid = 1;
inline bool SetUserStatusReq::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetUserStatusReq::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetUserStatusReq::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetUserStatusReq::clear_uid() {
  uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_uid();
}
inline const ::std::string& SetUserStatusReq::uid() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusReq.uid)
  return uid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_uid(const ::std::string& value) {
  set_has_uid();
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusReq.uid)
}
inline void SetUserStatusReq::set_uid(const char* value) {
  set_has_uid();
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:antalk.data.SetUserStatusReq.uid)
}
inline void SetUserStatusReq::set_uid(const char* value, size_t size) {
  set_has_uid();
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:antalk.data.SetUserStatusReq.uid)
}
inline ::std::string* SetUserStatusReq::mutable_uid() {
  set_has_uid();
  // @@protoc_insertion_point(field_mutable:antalk.data.SetUserStatusReq.uid)
  return uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetUserStatusReq::release_uid() {
  // @@protoc_insertion_point(field_release:antalk.data.SetUserStatusReq.uid)
  clear_has_uid();
  return uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_allocated_uid(::std::string* uid) {
  if (uid != NULL) {
    set_has_uid();
  } else {
    clear_has_uid();
  }
  uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uid);
  // @@protoc_insertion_point(field_set_allocated:antalk.data.SetUserStatusReq.uid)
}

// optional int32 dev_type = 2;
inline bool SetUserStatusReq::has_dev_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SetUserStatusReq::set_has_dev_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SetUserStatusReq::clear_has_dev_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SetUserStatusReq::clear_dev_type() {
  dev_type_ = 0;
  clear_has_dev_type();
}
inline ::google::protobuf::int32 SetUserStatusReq::dev_type() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusReq.dev_type)
  return dev_type_;
}
inline void SetUserStatusReq::set_dev_type(::google::protobuf::int32 value) {
  set_has_dev_type();
  dev_type_ = value;
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusReq.dev_type)
}

// optional string session = 3;
inline bool SetUserStatusReq::has_session() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SetUserStatusReq::set_has_session() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SetUserStatusReq::clear_has_session() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SetUserStatusReq::clear_session() {
  session_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_session();
}
inline const ::std::string& SetUserStatusReq::session() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusReq.session)
  return session_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_session(const ::std::string& value) {
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusReq.session)
}
inline void SetUserStatusReq::set_session(const char* value) {
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:antalk.data.SetUserStatusReq.session)
}
inline void SetUserStatusReq::set_session(const char* value, size_t size) {
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:antalk.data.SetUserStatusReq.session)
}
inline ::std::string* SetUserStatusReq::mutable_session() {
  set_has_session();
  // @@protoc_insertion_point(field_mutable:antalk.data.SetUserStatusReq.session)
  return session_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetUserStatusReq::release_session() {
  // @@protoc_insertion_point(field_release:antalk.data.SetUserStatusReq.session)
  clear_has_session();
  return session_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_allocated_session(::std::string* session) {
  if (session != NULL) {
    set_has_session();
  } else {
    clear_has_session();
  }
  session_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session);
  // @@protoc_insertion_point(field_set_allocated:antalk.data.SetUserStatusReq.session)
}

// optional int32 status = 4;
inline bool SetUserStatusReq::has_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SetUserStatusReq::set_has_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SetUserStatusReq::clear_has_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SetUserStatusReq::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 SetUserStatusReq::status() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusReq.status)
  return status_;
}
inline void SetUserStatusReq::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusReq.status)
}

// optional string login_info = 5;
inline bool SetUserStatusReq::has_login_info() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SetUserStatusReq::set_has_login_info() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SetUserStatusReq::clear_has_login_info() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SetUserStatusReq::clear_login_info() {
  login_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_login_info();
}
inline const ::std::string& SetUserStatusReq::login_info() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusReq.login_info)
  return login_info_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_login_info(const ::std::string& value) {
  set_has_login_info();
  login_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusReq.login_info)
}
inline void SetUserStatusReq::set_login_info(const char* value) {
  set_has_login_info();
  login_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:antalk.data.SetUserStatusReq.login_info)
}
inline void SetUserStatusReq::set_login_info(const char* value, size_t size) {
  set_has_login_info();
  login_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:antalk.data.SetUserStatusReq.login_info)
}
inline ::std::string* SetUserStatusReq::mutable_login_info() {
  set_has_login_info();
  // @@protoc_insertion_point(field_mutable:antalk.data.SetUserStatusReq.login_info)
  return login_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetUserStatusReq::release_login_info() {
  // @@protoc_insertion_point(field_release:antalk.data.SetUserStatusReq.login_info)
  clear_has_login_info();
  return login_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetUserStatusReq::set_allocated_login_info(::std::string* login_info) {
  if (login_info != NULL) {
    set_has_login_info();
  } else {
    clear_has_login_info();
  }
  login_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), login_info);
  // @@protoc_insertion_point(field_set_allocated:antalk.data.SetUserStatusReq.login_info)
}

// -------------------------------------------------------------------

// SetUserStatusResp

// optional .antalk.common.ResultType result = 1;
inline bool SetUserStatusResp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetUserStatusResp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetUserStatusResp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetUserStatusResp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::antalk::common::ResultType SetUserStatusResp::result() const {
  // @@protoc_insertion_point(field_get:antalk.data.SetUserStatusResp.result)
  return static_cast< ::antalk::common::ResultType >(result_);
}
inline void SetUserStatusResp::set_result(::antalk::common::ResultType value) {
  assert(::antalk::common::ResultType_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:antalk.data.SetUserStatusResp.result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace antalk

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_data_2eproto__INCLUDED
